In [92]:
import tensorflow as tf
import pandas as pd 
csv_file = pd.read_csv('./results/ADM_VRP_20_1024/data_pak_calc.csv')
df = csv_file['latitude-longitude'].head(20)



In [86]:
import tensorflow as tf

tensorList = ['33.678009,73.031488',
 '33.721182,73.082769',
 '33.652216,73.015807',
 '33.715528,73.017282',
 '33.716625,73.07991',
 '33.646957,73.161429',
 '33.649324,73.017126',
 '33.719812,73.03444',
 '33.7018928662,73.0538018524',
 '33.7126532671,73.037796725',
 '33.648845,73.040828',
 '33.64943,73.01726',
 '33.69953,73.05353',
 '33.6487970488,73.0406091051',
 '33.693119,73.056956',
 '33.6571865263,73.0696338564',
 '33.6323864807,73.1223405397',
 '33.7372742684,73.0932875168',
 '33.7434940689,73.0886076296',
 '33.7094208981,73.0840775542',]

# Split the strings on the comma
coords = tf.strings.split(tensorList, sep=',')
# Convert the strings to numbers
coords = tf.strings.to_number(coords)
# Stack the numbers into a tensor
coords = tf.stack(coords)
coord_reshaped = tf.reshape(coords, [1,20,2])

#Location of the main depo 
depo_base = [33.7111702,73.4285812]
depo_reshaped = tf.reshape(depo_base, [1, 2])

#Number of capacities 
CAPACITIES = {
            10: 20.,
            20: 30.,
            50: 40.,
            100: 50.
        }
seed = 1234
demand = (tf.cast(tf.random.uniform(minval=1, maxval=10, shape=(1, 20),
                                                        dtype=tf.int32, seed=seed), tf.float32) / tf.cast(CAPACITIES[20], tf.float32)
                                )


In [87]:
depo, graphs, demand = (tf.convert_to_tensor(depo_reshaped),
                        coord_reshaped, demand
                        
                        )

In [88]:
from utils import save_to_pickle
filename = "myDatase1"
save_to_pickle('Validation_dataset_{}.pkl'.format(filename), (depo, graphs, demand))


In [89]:
pd.read_pickle('./Validation_dataset_myDatase1.pkl')

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[33.71117, 73.42858]], dtype=float32)>,
 <tf.Tensor: shape=(1, 20, 2), dtype=float32, numpy=
 array([[[33.67801 , 73.03149 ],
         [33.721184, 73.08277 ],
         [33.652218, 73.01581 ],
         [33.715527, 73.01728 ],
         [33.716625, 73.07991 ],
         [33.646957, 73.16143 ],
         [33.649323, 73.01713 ],
         [33.71981 , 73.03444 ],
         [33.701893, 73.0538  ],
         [33.712654, 73.037796],
         [33.648846, 73.040825],
         [33.64943 , 73.01726 ],
         [33.69953 , 73.05353 ],
         [33.648796, 73.04061 ],
         [33.69312 , 73.05695 ],
         [33.65719 , 73.06963 ],
         [33.632385, 73.12234 ],
         [33.737274, 73.093285],
         [33.743496, 73.08861 ],
         [33.70942 , 73.084076]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 20), dtype=float32, numpy=
 array([[0.26666668, 0.06666667, 0.2       , 0.2       , 0.3       ,
         0.2       , 0.26666668, 0.1       , 0.2      